language: ruby
cache: bundler
gemfile: Gemfile
script:
  - gem install bundler
  - bundle exec jekyll build --trace
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 3.0
